//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voting.Ausmittlung.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voting.Ausmittlung.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eidg.
        /// </summary>
        internal static string Exports_DomainOfInfluenceType_Ch {
            get {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kantonal.
        /// </summary>
        internal static string Exports_DomainOfInfluenceType_Ct {
            get {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Ct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to bezrik.
        /// </summary>
        internal static string Exports_DomainOfInfluenceType_Bz
        {
            get
            {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Bz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kommunal.
        /// </summary>
        internal static string Exports_DomainOfInfluenceType_Other {
            get {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majorz.
        /// </summary>
        internal static string Exports_MajorityElection {
            get {
                return ResourceManager.GetString("Exports.MajorityElection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporz.
        /// </summary>
        internal static string Exports_ProportionalElection {
            get {
                return ResourceManager.GetString("Exports.ProportionalElection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebenwahl.
        /// </summary>
        internal static string Exports_SecondaryMajorityElection {
            get {
                return ResourceManager.GetString("Exports.SecondaryMajorityElection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstimmung.
        /// </summary>
        internal static string Exports_Vote {
            get {
                return ResourceManager.GetString("Exports.Vote", resourceCulture);
            }
        }
    }
}
