//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voting.Ausmittlung.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Voting.Ausmittlung.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exports_DomainOfInfluenceType_Ch {
            get {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Ch", resourceCulture);
            }
        }
        
        internal static string Exports_DomainOfInfluenceType_Ct {
            get {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Ct", resourceCulture);
            }
        }
        
        internal static string Exports_DomainOfInfluenceType_Mu {
            get {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Mu", resourceCulture);
            }
        }
        
        internal static string Exports_DomainOfInfluenceType_Other {
            get {
                return ResourceManager.GetString("Exports.DomainOfInfluenceType.Other", resourceCulture);
            }
        }
        
        internal static string Exports_Vote {
            get {
                return ResourceManager.GetString("Exports.Vote", resourceCulture);
            }
        }
        
        internal static string Exports_MajorityElection {
            get {
                return ResourceManager.GetString("Exports.MajorityElection", resourceCulture);
            }
        }
        
        internal static string Exports_SecondaryMajorityElection {
            get {
                return ResourceManager.GetString("Exports.SecondaryMajorityElection", resourceCulture);
            }
        }
        
        internal static string Exports_ProportionalElection {
            get {
                return ResourceManager.GetString("Exports.ProportionalElection", resourceCulture);
            }
        }
    }
}
