//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voting.Ausmittlung.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voting.Ausmittlung.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majorzwahl Korrektur beenden.
        /// </summary>
        internal static string MajorityElectionResult_CorrectionFinished {
            get {
                return ResourceManager.GetString("MajorityElectionResult.CorrectionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majorzwahl Endresultat finalisieren.
        /// </summary>
        internal static string MajorityElectionResult_FinalizeEndResult {
            get {
                return ResourceManager.GetString("MajorityElectionResult.FinalizeEndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majorzwahl Erfassung beenden.
        /// </summary>
        internal static string MajorityElectionResult_SubmissionFinished {
            get {
                return ResourceManager.GetString("MajorityElectionResult.SubmissionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporzwahl Korrektur beenden.
        /// </summary>
        internal static string ProportionalElectionResult_CorrectionFinished {
            get {
                return ResourceManager.GetString("ProportionalElectionResult.CorrectionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporzwahl Endresultat finalisieren.
        /// </summary>
        internal static string ProportionalElectionResult_FinalizeEndResult {
            get {
                return ResourceManager.GetString("ProportionalElectionResult.FinalizeEndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporzwahl Erfassung beenden.
        /// </summary>
        internal static string ProportionalElectionResult_SubmissionFinished {
            get {
                return ResourceManager.GetString("ProportionalElectionResult.SubmissionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstimmung Korrektur beenden.
        /// </summary>
        internal static string VoteResult_CorrectionFinished {
            get {
                return ResourceManager.GetString("VoteResult.CorrectionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstimmung Endresultat finalisieren.
        /// </summary>
        internal static string VoteResult_FinalizeEndResult {
            get {
                return ResourceManager.GetString("VoteResult.FinalizeEndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstimmung Erfassung beenden.
        /// </summary>
        internal static string VoteResult_SubmissionFinished {
            get {
                return ResourceManager.GetString("VoteResult.SubmissionFinished", resourceCulture);
            }
        }
    }
}
